### 회원가입

POST {{host}}/{{prefix}}/members/signup
Content-Type: application/json
Accept: application/json

{
  "nickname" : "PCloud"
}


### 정보 업데이트

POST {{host}}/{{prefix}}/members
Content-Type: application/json
Accept: application/json

{
  "nickname" : "PurpleCloud",
  "statusMessage": "Hello!"
}

